import { Injectable, BadRequestException, NotFoundException, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import * as fs from 'fs';
import * as path from 'path';
import { pipeline } from 'stream/promises';
import { v4 as uuidv4 } from 'uuid';
import { FileEntity } from '../../entities/file.entity';
import { UploadTokenEntity } from '../../entities/upload-token.entity';
import { UploadSessionEntity } from '../../entities/upload-session.entity';
import { ConfigService } from '@nestjs/config';
import { getDatePath } from '../../common/utils/date-path.util';
import { computeBufferHash, computeFileHash } from '../../common/utils/file-hash.util';

// UUID format: 32 hex chars (no hyphens, as generated by uuidv4().replace(/-/g, ''))
const UPLOAD_ID_REGEX = /^[a-f0-9]{32}$/i;

@Injectable()
export class UploadService {
  private uploadBaseDir: string;
  private baseUrl: string;

  constructor(
    @InjectRepository(FileEntity)
    private fileRepo: Repository<FileEntity>,
    @InjectRepository(UploadTokenEntity)
    private tokenRepo: Repository<UploadTokenEntity>,
    @InjectRepository(UploadSessionEntity)
    private sessionRepo: Repository<UploadSessionEntity>,
    private configService: ConfigService,
  ) {
    this.uploadBaseDir = this.configService.get<string>('uploadBaseDir');
    this.baseUrl = this.configService.get<string>('baseUrl');
  }

  /**
   * POST /upload/check — 客户端算好 hash，查重秒传
   */
  async checkFile(hash: string, filename: string, size: number) {
    if (!hash || !filename || !size) {
      throw new BadRequestException('缺少必要参数：hash、filename、size');
    }

    const existing = await this.fileRepo.findOne({ where: { hash } });

    if (existing) {
      return {
        exists: true,
        duplicated: true,
        fileName: existing.fileName,
        relativePath: existing.relativePath,
        fullUrl: existing.fullUrl,
        size: existing.size,
        hash: existing.hash,
      };
    }

    return { exists: false };
  }

  /**
   * POST /upload — 小文件直接上传（保留原有逻辑）
   */
  async handleUpload(
    buffer: Buffer,
    originalName: string,
    mimeType: string,
    size: number,
    clientHash?: string,
    token?: UploadTokenEntity,
  ) {
    const hash = computeBufferHash(buffer);

    // 如果前端传了 hash，校验一致性
    if (clientHash && clientHash !== hash) {
      throw new BadRequestException('文件哈希校验失败，文件可能已损坏');
    }

    // 查重
    const existing = await this.fileRepo.findOne({ where: { hash } });
    if (existing) {
      return {
        duplicated: true,
        fileName: existing.fileName,
        relativePath: existing.relativePath,
        fullUrl: existing.fullUrl,
        size: existing.size,
        hash: existing.hash,
      };
    }

    // 保存文件
    const result = await this.saveFileToDisk(buffer, originalName, mimeType, size, hash, token);
    return { duplicated: false, ...result };
  }

  /**
   * POST /upload/chunk — 切片上传
   */
  async uploadChunk(
    chunkBuffer: Buffer,
    uploadId: string,
    chunkIndex: number,
    token?: UploadTokenEntity,
  ) {
    // 防止路径遍历：uploadId 必须是 32 位 hex
    if (!UPLOAD_ID_REGEX.test(uploadId)) {
      throw new BadRequestException('无效的上传会话 ID');
    }

    // 查找 session
    const session = await this.sessionRepo.findOne({ where: { uploadId } });

    if (!session) {
      throw new NotFoundException('上传会话不存在，请先调用 /upload/check 创建');
    }

    if (session.status !== 'uploading') {
      throw new BadRequestException('该上传会话已完成或已过期');
    }

    if (chunkIndex < 0 || chunkIndex >= Number(session.totalChunks)) {
      throw new BadRequestException(`切片索引无效，有效范围：0-${Number(session.totalChunks) - 1}`);
    }

    // 校验切片大小：最后一个切片允许小于 chunkSize，其余不允许超过
    const isLastChunk = chunkIndex === Number(session.totalChunks) - 1;
    if (!isLastChunk && chunkBuffer.length > Number(session.chunkSize)) {
      throw new BadRequestException(`切片 ${chunkIndex} 大小 ${chunkBuffer.length} 超过限制 ${session.chunkSize}`);
    }
    // 所有切片都不允许超过 2x chunkSize（防止恶意上传）
    if (chunkBuffer.length > Number(session.chunkSize) * 2) {
      throw new BadRequestException(`切片 ${chunkIndex} 大小异常，远超 chunkSize`);
    }

    // 保存切片到临时目录（纯磁盘写入，无 DB 操作）
    const chunkDir = path.join(this.uploadBaseDir, '.chunks', uploadId);
    if (!fs.existsSync(chunkDir)) {
      fs.mkdirSync(chunkDir, { recursive: true });
    }

    const chunkPath = path.join(chunkDir, String(chunkIndex));
    fs.writeFileSync(chunkPath, chunkBuffer);

    return {
      uploadId: session.uploadId,
      chunkIndex,
      totalChunks: Number(session.totalChunks),
    };
  }

  /**
   * POST /upload/merge — 合并切片
   */
  private readonly logger = new Logger(UploadService.name);

  async mergeChunks(
    uploadId: string,
    filename: string,
    hash: string,
    totalChunks: number,
    token?: UploadTokenEntity,
  ) {
    // 防止路径遍历
    if (!UPLOAD_ID_REGEX.test(uploadId)) {
      throw new BadRequestException('无效的上传会话 ID');
    }

    const session = await this.sessionRepo.findOne({ where: { uploadId } });

    if (!session) {
      throw new NotFoundException('上传会话不存在');
    }

    // 状态校验：只允许 uploading 状态合并
    if (session.status !== 'uploading') {
      throw new BadRequestException('该上传会话已完成或已过期');
    }

    const chunkDir = path.join(this.uploadBaseDir, '.chunks', uploadId);

    try {
      // 从磁盘读取已上传切片，验证完整性
      const uploadedChunks = await this.getChunkFiles(uploadId);
      if (uploadedChunks.length !== totalChunks) {
        throw new BadRequestException(
          `切片不完整：已上传 ${uploadedChunks.length}/${totalChunks} 个切片`,
        );
      }

      // 查重（在读 chunks 之前查重可省 I/O，但 chunks 已读了，保持此处逻辑）
      const existing = await this.fileRepo.findOne({ where: { hash } });
      if (existing) {
        this.cleanupChunks(chunkDir);
        session.status = 'merged';
        await this.sessionRepo.save(session);

        return {
          duplicated: true,
          fileName: existing.fileName,
          relativePath: existing.relativePath,
          fullUrl: existing.fullUrl,
          size: existing.size,
          hash: existing.hash,
        };
      }

      // 合并切片 — 使用 stream/promises/pipeline 正确处理背压
      const datePath = getDatePath();
      const ext = path.extname(filename).toLowerCase();
      const fileName = `${uuidv4()}${ext}`;
      const relativePath = `uploads/${datePath}/${fileName}`;
      const fullDirPath = path.join(this.uploadBaseDir, datePath);

      if (!fs.existsSync(fullDirPath)) {
        fs.mkdirSync(fullDirPath, { recursive: true });
      }

      const fullPath = path.join(this.uploadBaseDir, datePath, fileName);
      const writeStream = fs.createWriteStream(fullPath);

      try {
        for (let i = 0; i < totalChunks; i++) {
          const chunkPath = path.join(chunkDir, String(i));
          const chunkReadStream = fs.createReadStream(chunkPath);
          await pipeline(chunkReadStream, writeStream, { end: false });
        }
        writeStream.end();
        await new Promise<void>((resolve, reject) => {
          writeStream.on('finish', resolve);
          writeStream.on('error', reject);
        });
      } catch (streamErr) {
        writeStream.destroy();
        if (fs.existsSync(fullPath)) {
          fs.unlinkSync(fullPath);
        }
        throw streamErr;
      }

      // 验证合并后的 hash
      const actualHash = await computeFileHash(fullPath);
      if (hash && actualHash !== hash) {
        fs.unlinkSync(fullPath);
        throw new BadRequestException('文件合并后哈希校验失败，请重新上传');
      }

      const fullUrl = `${this.baseUrl}/${relativePath}`;

      // 入库
      const fileRecord = this.fileRepo.create({
        originalName: filename,
        fileName,
        relativePath,
        fullUrl,
        hash: actualHash,
        hashAlgorithm: 'sha256',
        mimeType: session.mimeType || 'application/octet-stream',
        size: session.fileSize,
        tokenId: token?.id || session.tokenId || null,
        tokenName: token?.name || null,
      });
      await this.fileRepo.save(fileRecord);

      // 清理
      this.cleanupChunks(chunkDir);
      session.status = 'merged';
      await this.sessionRepo.save(session);

      return {
        duplicated: false,
        fileName,
        relativePath,
        fullUrl,
        size: session.fileSize,
        hash: actualHash,
      };
    } catch (err) {
      // 确保异常时也清理临时文件
      this.cleanupChunks(chunkDir);
      throw err;
    }
  }

  /**
   * GET /upload/progress/:uploadId — 断点续传查询
   */
  async getProgress(uploadId: string) {
    if (!UPLOAD_ID_REGEX.test(uploadId)) {
      throw new BadRequestException('无效的上传会话 ID');
    }

    const session = await this.sessionRepo.findOne({ where: { uploadId } });

    if (!session) {
      throw new NotFoundException('上传会话不存在');
    }

    // 从磁盘读取已上传的切片列表（零 DB 操作）
    const uploadedChunks = await this.getChunkFiles(uploadId);

    return {
      uploadId: session.uploadId,
      uploadedChunks,
      totalChunks: Number(session.totalChunks),
      chunkSize: session.chunkSize,
      status: session.status,
      originalName: session.originalName,
      fileSize: session.fileSize,
    };
  }

  /**
   * 创建切片上传会话（check 接口在文件不存在时调用）
   */
  async createSession(
    hash: string,
    filename: string,
    size: number,
    chunkSize: number,
    mimeType: string,
    token?: UploadTokenEntity,
  ) {
    // 如果这个 hash 已有进行中的会话，直接复用（续传场景）
    const existing = await this.sessionRepo.findOne({
      where: { fileHash: hash, status: 'uploading' },
    });
    if (existing) {
      return {
        uploadId: existing.uploadId,
        chunkSize: existing.chunkSize,
        totalChunks: existing.totalChunks,
      };
    }

    const totalChunks = Math.ceil(size / chunkSize);
    const uploadId = uuidv4().replace(/-/g, '');

    const session = this.sessionRepo.create({
      uploadId,
      fileHash: hash,
      originalName: filename,
      fileSize: size,
      chunkSize,
      totalChunks,
      mimeType,
      tokenId: token?.id || null,
      status: 'uploading',
    });

    await this.sessionRepo.save(session);

    return {
      uploadId,
      chunkSize,
      totalChunks,
    };
  }

  /**
   * 保存文件到磁盘并入库
   */
  private async saveFileToDisk(
    buffer: Buffer,
    originalName: string,
    mimeType: string,
    size: number,
    hash: string,
    token?: UploadTokenEntity,
  ) {
    const datePath = getDatePath();
    const ext = path.extname(originalName).toLowerCase();
    const fileName = `${uuidv4()}${ext}`;
    const relativePath = `uploads/${datePath}/${fileName}`;
    const fullDirPath = path.join(this.uploadBaseDir, datePath);

    if (!fs.existsSync(fullDirPath)) {
      fs.mkdirSync(fullDirPath, { recursive: true });
    }

    const fullPath = path.join(this.uploadBaseDir, datePath, fileName);
    fs.writeFileSync(fullPath, buffer);

    const fullUrl = `${this.baseUrl}/${relativePath}`;

    const fileRecord = this.fileRepo.create({
      originalName,
      fileName,
      relativePath,
      fullUrl,
      hash,
      hashAlgorithm: 'sha256',
      mimeType,
      size,
      tokenId: token?.id || null,
      tokenName: token?.name || null,
    });

    await this.fileRepo.save(fileRecord);

    return { fileName, relativePath, fullUrl, size, hash };
  }

  /**
   * 从磁盘读取已上传的切片索引列表
   */
  private async getChunkFiles(uploadId: string): Promise<number[]> {
    const chunkDir = path.join(this.uploadBaseDir, '.chunks', uploadId);
    try {
      const files = await fs.promises.readdir(chunkDir);
      return files
        .map(name => parseInt(name, 10))
        .filter(n => !isNaN(n))
        .sort((a, b) => a - b);
    } catch {
      return [];
    }
  }

  /**
   * 清理临时切片目录
   */
  private cleanupChunks(chunkDir: string) {
    if (fs.existsSync(chunkDir)) {
      fs.rmSync(chunkDir, { recursive: true, force: true });
    }
  }
}
